fzf.el

If ``fzf/args`` is something like "-x --color=no" the plugin refuses to work. This tiny patch fixes the issue for me.

Fix fzf arguments handling

---

fzf.el

This patch fixes wrong (really, don't think it was made by design) plugin behavior when projectile is installed but fzf is called outside a project. In this case projectile returns an error and fzf fails to start. Applying this patch will make fzf to search in the current buffer directory in case projectile-project-root function returns error.

Search in current directory if not in project

---

fzf.el

Previously, when fzf finished and printed to the terminal buffer a path
that was wider than the Emacs window, term mode was adding a newline at
each place where the path reached the right edge of the window and
needed to wrap to the next line.  With this change, term mode does not
add any newlines, so fzf can safely deliver long paths back to Emacs.

Bugfix: allow selection of paths wider than Emacs window

---

fzf.el

I repeatedly had the problem of fzf erroring with:
(wrong-type-argument stringp nil)
and not working again until I restarted Emacs.  Turning on tracebacks
with `M-x toggle-debug-on-error` showed that the error, confusingly, was
in a call that did not even have a `nil` argument:
start-process("fzf" #<buffer *fzf*> "/bin/sh" "-c" "stty..." "fzf" "-x")
The `start-process` C code, however, uses another value in addition to
its explicit arguments: the current buffer’s `default-directory`.  I
added some debug statements and verified that once the current directory
of the `*fzf*` buffer first becomes `nil`, fzf never recovers.  In other
words, the sequence of calls:
(fzf/start "~/project")    ;; works fine
(fzf/start nil)            ;; dies with wrong-type-argument, as expected
(fzf/start …

Make `(fzf/start nil)` not permanently break fzf

---

fzf.el

`(set-window-margins nil 1)`
Was causing unexpected and buggy parsing of line breaks over the output of fzf: https://i.imgur.com/UC0EUKq.png

Removed buggy line-break behavior on emacs over terminal

---

fzf.el

`visual-line-mode` seems incompatible with term buffers, specifically
that used by FZF. Some users enable the mode globally (e.g., via
`global-visual-line-mode`). This explicitly turns off the mode for
FZF buffers.
Fixes #28.

READY FOR REVIEW - Disable visual-line-mode for FZF buffers

---

fzf.el

Emacs 26 adds builtin line numbers - need to disable those too to
ensure the terminal width ends up correct.

Support Emacs 26 native line numbers

---

fzf.el

File fails to open because of whitespace in the selected filename
Env:
OSX with fzf installed via brew and Emacs for OSX v26.3

trimming selection

---

README.md
fzf.el

This pull request rebases https://github.com/bling/fzf.el/pull/39  to master so it can be merged.
Instead of deleting existing functions that fzf.el exposed, such as `fzf-git`, I rewrote the functions to use the new `fzf/start` so users won't have their existing configs broken.

Generalize fzf.el into a completion engine with fzf

---

fzf.el

This pull request is to fix issue #64. Thanks.

Fix #64: fzf show only files in a directory of fzf executable

---

fzf.el

When `fzf-switch-buffer` is called, directory will be nil, causing Emacs to report error:
```
error in process sentinel: concat: Wrong type argument: stringp, nil
```
This commit checks if directory is nil and ignore file-name-as-directory call in that case.

Prevent error when fzf-switch-buffer is called

---

README.md
fzf.el

- Add customizable option `fzf/grep-command` for the default `grep` command. Default is `grep -nrH` (same as before)
- Slight refactor of `fzf-grep`
- Use `fzf/start` instead of `fzf-with-command` now that `fzf/start` supports commands
- Use `fzf/grep-command` to allow user customization
- Use `fzf/resolve-directory` instead of `default-directory`. This will function the same as it is currently except if in a `projectile` project, in which case the root of the project is used. 
- Add `fzf-grep-dwim` to lookup `thing-at-point`
I also added a section to the README showing customization options.

Make `grep` configurable and add `fzf/grep-dwim`

---

README.md
fzf.el

> **Note**: This PR is heavily informed by the [`fzf` advanced use documentation](https://github.com/junegunn/fzf/blob/master/ADVANCED.md). For complete context, do read the documentation. Although the documentation mentions `ripgrep` specifically, the ideas expand to any kind of custom narrowing (although the performance gain may not)
*__in descending priority order__*
- Reintroduce `FZF_DEFAULT_COMMAND` usage to support custom narrowing 
- From the `fzf` documentation:
> Instead of starting fzf in `rg ... | fzf` form, we start fzf without an explicit input, but with a custom FZF_DEFAULT_COMMAND variable. This way fzf can kill the initial Ripgrep process it starts with the initial query. Otherwise, the initial Ripgrep process will keep consuming system resources even after reload is …

Add support for custom narrowing

---

fzf.el

(linum-mode 0) was causing fzf to not work in the Emacs 29 build of 2022-10-20. After adding a conditional statement for running this funtion that checks the version of Emacs, it was working again.

Fix fzf not working in Emacs 29 build 2022-10-20

---

fzf.el

Small backwards-compatible change for `find-file-in-dir` that uses `read-directory-name` instead of a required interactive arg to get mini buffer completion on directory names (i.e. type ".co" TAB complete to ".config").

use read-directory-name for find-file-in-dir

---

fzf.el

Which prevented its customization to work properly.
There is no 'bool type.  It's 'boolean.

Fix fzf/position-bottom defcustom type declaration bug & fix byte compiler warnings

---

fzf.el

The first part  and some other changes of the set were already merged in bling master.  The remaining include more warning fixes and error handling logic improvements:
- the `fboundp` calls need quoted symbols as arguments, not pound quoted.
- there might be **no** recent files (or the recentf.el is not loaded): account for that and report a user error.
- even if `require` is used to load a file, its functions and variables must be declared otherwise the byte-compiler  complains when the require is inside a form.  
- For function: add a `fboundp` check conditional.
- For variable: add a defvar form that does not set the initial value.

More byte-compiler warning fixes & error handling improvements

---

fzf.el

Fixes:
- https://github.com/bling/fzf.el/issues/84
- https://github.com/bling/fzf.el/issues/82
'fzf/after-term-handle-exit' now detect extra spaces or other characters at the end of the file name returned by extraction of fzf output.
This occurs since fzf 0.35.1 as reported by issue #82 because of a new separator line.  But instead of modifying the command line the function trims any whitespace at the end of the file name.  If the resulting file name is not found it tries to extract the correct file name by removing characters at the end until a valid filename is found.  If it does not find any valid file name it then issues a descriptive message to provide enough info for further improvements.
Also included fix for issue #87 as well as other cleanup:
The following functions are no longer …

Issue #84 Fix.  Also fixes issue #82.

---

fzf.el

This addresses [issue #12](https://github.com/bling/fzf.el/issues/12) making user aware when Emacs can't access fzf executable instead of silently failing.

All commands user-error when fzf/executable not in PATH

---

fzf.el

- Fix regression in `fzf--action-find-file-with-line` introduced when changed code to use forward-line. The function moved to 1 line below the target. It now moves to the proper line.
-  Refactoring:
- Rename `fzf/window-register` to `fzf--window-register`, since   the register is not meant to be used by user code.
- Also clarified its docstring.
- Clarified `fzf-grep` docstring.
- Regrouping: 
- Move `fzf-git-grep` inside the VCS-related command code area.

Fix regression on fzf grep command + minor improvements

---

fzf.el

Changed the file name and line number extraction logic of a grep-like operation to use **Emacs Lisp regular expression**, allowing extraction of file names with any embedded characters (including colons) while also allowing user code to override the regular expression and the matching groups used to extract the file and line numbers.
- Add a new command, `fzf-hg-grep`, which produces a FILE:REV:LINE:text output and therefore requires a different regexp/matching groups to extract the file name and line numbers.
- Provide extraction expressions in a 3-item list of format described in `fzf--extractor-list` doctring.  The extraction for grep uses the `fzf--file-lnum-regexp` regexp, while extraction for hg grep uses the `fzf--file-rnum-lnum-regexp` regexp.
- Users can also override the …

New, more flexible filename/line extraction logic.

---

fzf.el

This addresses regression issue https://github.com/bling/fzf.el/issues/91 .
The problem was caused by `fzf-with-entries` using the file validator instead or the pass-through validator.  The new version of `fzf-with-entries` uses the pass-through validator by default and allows the user to specify another validator by a new optional argument.

Fix regression described in issue #91

---

fzf.el

Add fzf-find-in-buffer originally proposed by LiuYinCarl in https://github.com/bling/fzf.el/issues/94
- I modified the proposed code a little to adapt to the current code and added protection against trying to search in a buffer that is not visiting a file, an prompt to save the buffer if it has been modified.
Plus:
- Added a description of the limitations of the dwim commands when using grep.
- Small optimization:  ```(- v 1)``` --> ```(1- v)```

Add fzf-find-in-buffer (by LiuYinCarl)

---

fzf.el

The `fzf-grep-dwim` and `fzf-grep-dwim-with-narrowing` commands can now be invoked with a command prefix, like C-u.  When that's done the commands prompt for the file pattern to use.  Otherwise they use the default file pattern identified by the new `fzf/grep-file-pattern` customizable user-option.
- All prompts for grep operations now have a prompt history which can be invoked during the minibuffer prompt operation with M-p and M-p.  By default the history is kept independent for each major mode. If you prefer a global prompt history, shared across all major modes, then set the new `fzf/prompt-history-per-major-mode` customizable user-option to nil.
- Removed the limitation notes in the grep dwim commands as they no longer apply.
-Add `:safe` attribute to the boolean user-options.
Fix …

More flexible dwim grep with prompt history

---

fzf.el

Addresses issue https://github.com/bling/fzf.el/issues/101
- Add the new `fzf/args-for-preview` user-option.  This identifies the extra
command line options applied to the fzf OS command when the `fzf`,
`fzf-directory` fzf-projectile` and `fzf-recentf` Emacs commands are invoked with a prefix directory.
- `fzf/args-for-preview` default is to preview the top of the file's content.
The command line argument can be customized.  Five options are provided, allowing
independent maintenance of five different command lines to select and use.

Add support for file preview for `fzf`, `fzf-directory`, `fzf-projectile` and `fzf-recentf` 

---

fzf.el

The current message simply shows "FZF exited with code 0" when FZF operation suceeded. This message might have been useful during debugging but it's not very useful for users.
That is replaced with the following:
- On success, message shows a description of what was actually selected; a file name (with full path), file name, line number and line text, or the line number and line text depending of the type of command executed.
- On error, a user-error shows the FZF error.
The success message is most useful when a user wants to remember what file was previously selected by the FZF operation.

More informative message on FZF selection.

---

fzf.el

When a fzf/executable is specified by a path name, the process name is not the path but just the last path of it: the file name of the executable.

Fix #105: allow fzf/executable to be specified by path name

---

fzf.el

Ideally I'd have time to refactor the whole file and simplify the handling of validator.  But I have limited time at the moment.

Fix #113: fzf-with-command now use fzf--pass-through validator by default.

---

fzf.el

Modified the code to determine the true root directory. 
By using `file-truename` on `default-directory`, we resolve any symlinks, 
ensuring we get the actual physical location even if we're currently within a symlinked directory.
Example Scenario:
1. Dotfiles are version-controlled in the '~/sync' directory.
2. A symlink '~/.emacs.d' is created from '~/sync/.../emacs-configuration'.
3. If the `default-directory` is set under '~/.emacs.d', the original function fails to find the project root, as it doesn't resolve the symlink and searches within the symbolic link's hierarchy.
This patch fixes this behavior by ensuring we search the actual physical location by resolving any symlinks with `file-truename`.

Resolve symlinks in the base vcs command
